"""Deterministic block-page fingerprints. Pure string matching — no LLM.

Used by the classifier's NEGATIVE phase. Three layers, checked in this order:
  1. INTERSTITIAL_TITLES — <title> text that ONLY ever appears on a challenge/block
     interstitial. Highest precision -> fired UNGATED (a real page's title is its
     own name, never "Just a moment").
  2. CHALLENGE_HOSTS    — third-party hosts a wall loads its widget/sensor from.
     Stable even when the visible text localizes. Fired only when the body is THIN
     (host present on a rich page = a real page embedding a captcha widget, e.g. a
     contact form — NOT a block).
  3. BLOCK_SIGNATURES   — body substrings. Also thin-gated (a long article that merely
     mentions a vendor isn't blocked).

High precision is the goal: a false positive here causes needless (paid) escalation.
Extend these as you meet new walls in production.
"""
from __future__ import annotations

# 1. Interstitial <title> text — UNGATED. These titles never appear on real content.
INTERSTITIAL_TITLES: list[tuple[str, list[str]]] = [
    ("cloudflare_challenge", ["just a moment", "attention required", "please wait"]),
    ("vercel_checkpoint", ["vercel security checkpoint"]),
    ("imperva_incapsula", ["pardon our interruption"]),
    ("akamai", ["access denied"]),
    ("queue_it", ["you are now in line", "waiting room"]),
    ("datadome", ["please enable js and disable any ad blocker"]),
    ("google_sorry", ["before you continue", "unusual traffic"]),
    ("generic_denied", ["access to this page has been denied", "are you a robot",
                        "verify you are human", "security check", "checking your browser"]),
]

# 2. Challenge asset hosts — thin-gated. A wall's widget/sensor loads from these.
CHALLENGE_HOSTS: list[tuple[str, list[str]]] = [
    ("cloudflare_challenge", ["challenges.cloudflare.com"]),
    ("turnstile", ["challenges.cloudflare.com/turnstile"]),
    ("vercel_checkpoint", ["vercel.live/_next-live", "/_vercel/", "vercel-challenge"]),
    ("datadome", ["geo.captcha-delivery.com", "js.datadome.co", "captcha-delivery.com"]),
    ("perimeterx", ["captcha.px-cloud.net", ".perimeterx.net", "px-cdn"]),
    ("aws_waf", ["token.awswaf.com", ".awswaf.com"]),
    ("kasada", [".kasada.io", "/kpsdk-cd", "/kpsdk-ip"]),
    ("imperva_incapsula", ["/_incapsula_resource"]),
    ("recaptcha", ["www.google.com/recaptcha", "recaptcha.net"]),
    ("hcaptcha", ["hcaptcha.com/1/api.js", "js.hcaptcha.com"]),
    ("queue_it", [".queue-it.net"]),
]

# 3. Body substrings — thin-gated.
BLOCK_SIGNATURES: list[tuple[str, list[str]]] = [
    ("cloudflare_challenge", [
        "just a moment", "cf-chl", "cf_chl", "checking your browser",
        "cf-browser-verification", "_cf_chl_opt", "cf-mitigated",
    ]),
    ("cloudflare_block", ["attention required", "cloudflare ray id", "error 1020"]),
    ("vercel_checkpoint", ["vercel security checkpoint", "vercel-challenge"]),
    ("datadome", ["datadome", "geo.captcha-delivery.com", "dd_cookie", "x-datadome"]),
    ("imperva_incapsula", [
        "pardon our interruption", "_incapsula_", "incapsula incident",
        "/_incapsula_resource",
    ]),
    ("akamai", ["errors.edgesuite.net", "reference #18.", "akamai reference"]),
    ("perimeterx", ["px-captcha", "perimeterx", "captcha.px-cloud", "_pxhd", "_px2"]),
    ("aws_waf", ["awswaf", "token.awswaf.com", "awswafintegration"]),
    ("kasada", ["kpsdk", "kasada"]),
    ("turnstile", ["challenges.cloudflare.com/turnstile", "cf-turnstile"]),
    ("hcaptcha", ["hcaptcha.com/1/api.js", "h-captcha"]),
    ("recaptcha", ["www.google.com/recaptcha", "g-recaptcha", "grecaptcha.render"]),
    ("queue_it", ["queue-it.net", "you are now in line"]),
    ("sucuri", ["sucuri website firewall", "access denied - sucuri", "cloudproxy"]),
    ("wordfence", ["generated by wordfence"]),
    ("generic_denied", [
        "access to this page has been denied", "you have been blocked",
        "are you a robot", "verify you are a human", "access denied",
    ]),
]

# Captcha-family: an IP swap (L3) will NOT fix these — they need a challenge solver
# (L2C/Byparr/L4). Used by the escalator for smart routing. NOTE: cloudflare_challenge
# and vercel_checkpoint are JS challenges that clear with a browser+wait, so they are
# NOT here — they escalate to the next browser tier, not straight to a paid solver.
CAPTCHA_SIGNATURES = {
    "turnstile", "hcaptcha", "recaptcha", "datadome", "perimeterx", "aws_waf", "kasada",
}

# Resource URL patterns blocked at browser tiers — load HTML + JS only.
BLOCKED_URL_PATTERNS = [
    "*.css", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.svg", "*.ico",
    "*.woff", "*.woff2", "*.ttf", "*.otf", "*.eot",
    "*.mp4", "*.webm", "*.mp3", "*.avi", "*.mov",
    "*.pdf", "*google-analytics*", "*googletagmanager*", "*doubleclick*",
    "*facebook.com/tr*", "*hotjar*", "*segment.io*",
]


def find_interstitial_title(title_lower: str) -> str | None:
    """Layer 1 — ungated. Match against <title> text only (very high precision)."""
    if not title_lower:
        return None
    for name, needles in INTERSTITIAL_TITLES:
        for n in needles:
            if n in title_lower:
                return name
    return None


def find_challenge_host(html_lower: str) -> str | None:
    """Layer 2 — caller thin-gates. A challenge asset host referenced in the body."""
    for name, needles in CHALLENGE_HOSTS:
        for n in needles:
            if n in html_lower:
                return name
    return None


def find_block_signature(html_lower: str) -> str | None:
    """Layer 3 — caller thin-gates. A block-page body substring."""
    for name, needles in BLOCK_SIGNATURES:
        for n in needles:
            if n in html_lower:
                return name
    return None
